[project]
name = "opti-diagnose-serve"
version = "0.1.0"
description = "Serve models for diagnosing eye diseases"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch-model-archiver>=0.12.0",
    "torch>=2.5.1",
    "torchserve>=0.12.0",
    "torchvision>=0.20.1",
]
